// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./mock/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/alexey-dobry/medical-service/internal/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialsRepository is a mock of CredentialsRepository interface.
type MockCredentialsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialsRepositoryMockRecorder is the mock recorder for MockCredentialsRepository.
type MockCredentialsRepositoryMockRecorder struct {
	mock *MockCredentialsRepository
}

// NewMockCredentialsRepository creates a new mock instance.
func NewMockCredentialsRepository(ctrl *gomock.Controller) *MockCredentialsRepository {
	mock := &MockCredentialsRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepository) EXPECT() *MockCredentialsRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCredentialsRepository) Add(userCredentials model.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", userCredentials)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCredentialsRepositoryMockRecorder) Add(userCredentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCredentialsRepository)(nil).Add), userCredentials)
}

// Close mocks base method.
func (m *MockCredentialsRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCredentialsRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCredentialsRepository)(nil).Close))
}

// GetOneByID mocks base method.
func (m *MockCredentialsRepository) GetOneByID(userID uuid.UUID) (model.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByID", userID)
	ret0, _ := ret[0].(model.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByID indicates an expected call of GetOneByID.
func (mr *MockCredentialsRepositoryMockRecorder) GetOneByID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByID", reflect.TypeOf((*MockCredentialsRepository)(nil).GetOneByID), userID)
}

// GetOneByMail mocks base method.
func (m *MockCredentialsRepository) GetOneByMail(email string) (model.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByMail", email)
	ret0, _ := ret[0].(model.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByMail indicates an expected call of GetOneByMail.
func (mr *MockCredentialsRepositoryMockRecorder) GetOneByMail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByMail", reflect.TypeOf((*MockCredentialsRepository)(nil).GetOneByMail), email)
}
